import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import BaseContainer from "./common-components/base-container/base-container";
import { background, bodyWrapper } from "./styles/backgorund.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta charSet="UTF-8" />

      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
     
    </head>

    <body className={bodyWrapper}> 



      <BaseContainer className={background}>
   
                {children}
              
      
       </BaseContainer>
       


    

    </body>
  </html>
  );
}
